### ISSUE TITLE
Pass in config to adapters

### ISSUE THREAD

**Issue by thec0keman** [jsonapi-suite/jsonapi_compliable#147]
We are building a custom adapter and the existing abstractions are very helpful in this process.

The one piece that would be nice is if the `config` option from the resource was automatically passed in to new adapters.  Hacking this is simple enough, but we are finding several use cases (like storing additional configuration options in the resource and the adapter changing it's behavior based on certain filters).

**Comment by richmolj** [comment]
This project is becoming [Graphiti](https://graphiti-api.github.io/graphiti/guides/) and should have better internals to help here. It is on my short-term todo list to update the readme and redirect. Let me know if you run into the same issues though.

**Comment by richmolj** [comment]
FWIW Graphiti is the 1.0 version of this gem so is very similar, just better.

**Comment by thec0keman** [comment]
Awesome, thanks!
