### ISSUE TITLE
destroyed objects rendering

### ISSUE THREAD

**Issue by klobuczek** [jsonapi-suite/jsonapi_compliable#24]
Looks like  `render_jsonapi(object)`is not checking the `object.destroyed?` method and tries to serialize that object rather than returning no content with 204 or just meta with 200.
This is the spec part: http://jsonapi.org/format/#crud-deleting
I am more than willing to work on this if you share your ideas how and where you planned to implement this.

**Comment by richmolj** [comment]
I'm not totally opposed to adding "out of the box" support, but currently I think users can do this on their own:

```ruby
def destroy
  post = Post.find(1)
  if post.destroy
    render jsonapi: nil, meta: { foo: 'bar' }, status: 200
    # or
    return head(:no_content)
  else
    render_errors_for(post)
  end
end
```

Would that work for you?

**Comment by klobuczek** [comment]
Yes. That's what I ended up doing. I was just confused since the [documentation](https://github.com/jsonapi-suite/employee_directory/compare/step_17_basic_update...step_18_basic_destroy#diff-9c2813b29ae6d552435eefae3d881890R40) suggested calling `render_jsonapi` on the destroyed object which is the rails way, but I could not find anything corresponding in the code.

**Comment by richmolj** [comment]
Yep, I think it's really whether or not you prefer the Rails default or pure compliance. The docs could definitely be improved here.

**Comment by daniel-sullivan** [comment]
Just in case anyone comes across this via Google (it's the top result for 'render_jsonapi status', it is possible to set the return status from the render_jsonapi method itself by:

`render_jsonapi company, scope: false, status: 201`

It's not possible to use:  `render jsonapi: company, status: 201` if you are relying on the @context variable in any of your serializers as this is set and passed by `render_jsonapi`
