### ISSUE TITLE
No interface to discriminently disable pagination for resource

### ISSUE THREAD

**Issue by Dishwasha** [jsonapi-suite/jsonapi_compliable#47]
There are some cases where we want a query to not use the default pagination.  Using JSORM we could use Scope.prototype.per to some large size, but this doesn't feel right.  It would be better if we could do something like `.per(-1)` and have jsonapicompliable resources not use pagination for that query instance.

**Comment by richmolj** [comment]
JSORM does not automatically paginate. Are you sure this isn't happening at the server level?

**Comment by wadetandy** [comment]
Yes this is happening at the server level. When suggesting the JSORM
params, he was more referring to the page[size] params as it is currently
handled by the active record adapter.

**Comment by richmolj** [comment]
I suggest using `scope.per(1000)`/`?page[size]=1000`. 1,000 is currently the maximum page size and is functionally equivalent to `-1`. I'd like to get more data before adding something like `-1` - let's use the explicit 1,000 for now and see if it's a problem.
