### ISSUE TITLE
Sequel adapter

### ISSUE THREAD

**Issue by jnylen** [jsonapi-suite/jsonapi_compliable#51]
Hi,
Any idea if you will add an Sequel adapter?
It's way faster than AR and works with non-Rails frameworks quite well.

**Comment by richmolj** [comment]
Hey @jnylen - I would love to, but as I don't use Sequel in my day to day it's probably not coming anytime soon.

That said, you can A) use Sequel without an adapter or B) build it yourself!

An initial start might be [this simple little Sinatra app I wrote](https://github.com/jsonapi-suite/jsonapi_suite_sinatra_sample/blob/master/app.rb) that uses Sequel.

Also check out [How to Build an Adapter](https://jsonapi-suite.github.io/jsonapi_suite/how-to-build-an-adapter) - actually not that hard!

**Comment by jnylen** [comment]
Alright, @richmolj.
I'll try to look into it soon.

Better to check than start coding and it being released before i'm done. ;)

**Comment by richmolj** [comment]
Excited to see what you come up with @jnylen! Feel free to reach out if you run into any problems (email richmolj@gmail.com for slack invite if you'd like)
