### ISSUE TITLE
Docs not updated

### ISSUE THREAD

**Issue by zoran** [jsonapi-suite/jsonapi_compliable#8]
I just tried the new version but wasn't able to get it running.
- shall we use `allow_sideload` instead of `includes whitelist:` ?
- what is causing the error `ERROR: RuntimeError: you must override #order in an adapter subclass` ?

We're looking forward for the updated docs https://jsonapi-suite.github.io/jsonapi_compliable

Thanks a lot

**Comment by richmolj** [comment]
@zoran apologies for the late response, did not see this come in. View latest docs at https://jsonapi-suite.github.io/jsonapi_suite (the readme for this repo now points there).

**Comment by richmolj** [comment]
@zoran if that does not answer your questions please re-open
