### ISSUE TITLE
Sideloading / include no longer works in newest version

### ISSUE THREAD

**Issue by bastianl** [jsonapi-suite/jsonapi_compliable#9]
Running `bundle update` and updating: `jsonapi_compliable 0.5.3 (was 0.5.1)` results in the `?include` parameter no longer loading resources under the include hash. Is this a bug? Or a change in configuration?

Thanks.

**Comment by richmolj** [comment]
@bastianl please view the latest documentation - sideloads are applied in a different way, now. This is a good thing - you can now filter/paginate/sort/etc associations for free! Bear with me on the backwards-incompatibility as this is a WIP...though I expect the API to no longer undergo major changes and hope to get a 1.0 out shortly.

**Comment by richmolj** [comment]
@bastianl please re-open if that doesn't fix your issue
